import 'package:companion_animal/model/models.dart';

class DummyData {
  // 반려동물 더미 데이터
  static final List<Pet> pets = [
    Pet(
      id: 'pet1',
      name: '몽이',
      type: '강아지',
      breed: '포메라니안',
      imageUrl: 'assets/pets/pet1.jpg',
      birthDate: DateTime(2020, 3, 15),
    ),
    Pet(
      id: 'pet2',
      name: '까미',
      type: '고양이',
      breed: '러시안블루',
      imageUrl: 'assets/pets/pet2.jpg',
      birthDate: DateTime(2021, 5, 20),
    ),
    Pet(
      id: 'pet3',
      name: '초코',
      type: '강아지',
      breed: '말티즈',
      imageUrl: 'assets/pets/pet3.jpg',
      birthDate: DateTime(2019, 8, 10),
    ),
    Pet(
      id: 'pet4',
      name: '나비',
      type: '고양이',
      breed: '페르시안',
      imageUrl: 'assets/pets/pet4.jpg',
      birthDate: DateTime(2022, 1, 5),
    ),
    Pet(
      id: 'pet5',
      name: '콩이',
      type: '강아지',
      breed: '시바견',
      imageUrl: 'assets/pets/pet5.jpg',
      birthDate: DateTime(2021, 11, 30),
    ),
    Pet(
      id: 'pet6',
      name: '보리',
      type: '강아지',
      breed: '웰시코기',
      imageUrl: 'assets/pets/pet6.jpg',
      birthDate: DateTime(2020, 7, 25),
    ),
    Pet(
      id: 'pet7',
      name: '달이',
      type: '고양이',
      breed: '스코티시폴드',
      imageUrl: 'assets/pets/pet7.jpg',
      birthDate: DateTime(2021, 4, 12),
    ),
    Pet(
      id: 'pet8',
      name: '해피',
      type: '강아지',
      breed: '골든리트리버',
      imageUrl: 'assets/pets/pet8.jpg',
      birthDate: DateTime(2019, 12, 3),
    ),
  ];

  // 사용자 더미 데이터
  static final List<User> users = [
    User(
      id: 'user1',
      name: '김멍멍',
      email: 'kim@example.com',
      profileImageUrl: 'assets/profiles/profile1.jpg',
      pets: [pets[0], pets[1]],
      followerCount: 1200,
      followingCount: 300,
    ),
    User(
      id: 'user2',
      name: '박냥냥',
      email: 'park@example.com',
      profileImageUrl: 'assets/profiles/profile2.jpg',
      pets: [pets[2]],
      followerCount: 800,
      followingCount: 250,
    ),
    User(
      id: 'user3',
      name: '이토끼',
      email: 'lee@example.com',
      profileImageUrl: 'assets/profiles/profile3.jpg',
      pets: [pets[3]],
      followerCount: 1500,
      followingCount: 400,
    ),
    User(
      id: 'user4',
      name: '최햄스터',
      email: 'choi@example.com',
      profileImageUrl: 'assets/profiles/profile4.jpg',
      pets: [pets[4]],
      followerCount: 600,
      followingCount: 200,
    ),
    User(
      id: 'user5',
      name: '정펫맘',
      email: 'jung@example.com',
      profileImageUrl: 'assets/profiles/profile5.jpg',
      pets: [pets[5]],
      followerCount: 2000,
      followingCount: 500,
    ),
    User(
      id: 'user6',
      name: '강댕댕',
      email: 'kang@example.com',
      profileImageUrl: 'assets/profiles/profile6.jpg',
      pets: [pets[6]],
      followerCount: 900,
      followingCount: 350,
    ),
    User(
      id: 'user7',
      name: '윤멍냥',
      email: 'yoon@example.com',
      profileImageUrl: 'assets/profiles/profile7.jpg',
      pets: [pets[7]],
      followerCount: 1100,
      followingCount: 280,
    ),
    User(
      id: 'user8',
      name: '조뽀삐',
      email: 'cho@example.com',
      profileImageUrl: 'assets/profiles/profile8.jpg',
      pets: [pets[0]],
      followerCount: 750,
      followingCount: 220,
    ),
    User(
      id: 'user9',
      name: '한냥이',
      email: 'han@example.com',
      profileImageUrl: 'assets/profiles/profile9.jpg',
      pets: [pets[1]],
      followerCount: 1300,
      followingCount: 420,
    ),
    User(
      id: 'user10',
      name: '송펫집사',
      email: 'song@example.com',
      profileImageUrl: 'assets/profiles/profile10.jpg',
      pets: [pets[2]],
      followerCount: 950,
      followingCount: 310,
    ),
  ];

  // 비디오 더미 데이터
  static final List<PetVideo> videos = [
    PetVideo(
      id: 'video1',
      videoUrl: 'assets/videos/video1.mp4',
      petName: '몽이',
      petType: '강아지',
      breed: '포메라니안',
      description: '몽이의 첫 산책🐕 #첫산책 #귀여움 #포메라니안',
      createdAt: DateTime.now().subtract(Duration(days: 2)),
      likeCount: 1200,
      commentCount: 85,
      ownerId: 'user1',
      ownerName: '김멍멍',
      ownerProfileImage: 'assets/profiles/profile1.jpg',
      tags: ['#첫산책', '#귀여움', '#포메라니안'],
    ),
    PetVideo(
      id: 'video2',
      videoUrl: 'assets/videos/video2.mp4',
      petName: '까미',
      petType: '고양이',
      breed: '러시안블루',
      description: '까미의 장난감 놀이😺 #고양이 #장난감 #러시안블루',
      createdAt: DateTime.now().subtract(Duration(days: 1)),
      likeCount: 800,
      commentCount: 45,
      ownerId: 'user2',
      ownerName: '박냥냥',
      ownerProfileImage: 'assets/profiles/profile2.jpg',
      tags: ['#고양이', '#장난감', '#러시안블루'],
    ),
    PetVideo(
      id: 'video3',
      videoUrl: 'assets/videos/video3.mp4',
      petName: '초코',
      petType: '강아지',
      breed: '말티즈',
      description: '초코의 목욕시간🛁 #말티즈 #목욕 #강아지',
      createdAt: DateTime.now().subtract(Duration(hours: 12)),
      likeCount: 950,
      commentCount: 62,
      ownerId: 'user3',
      ownerName: '이토끼',
      ownerProfileImage: 'assets/profiles/profile3.jpg',
      tags: ['#말티즈', '#목욕', '#강아지'],
    ),
    PetVideo(
      id: 'video4',
      videoUrl: 'assets/videos/video4.mp4',
      petName: '나비',
      petType: '고양이',
      breed: '페르시안',
      description: '나비의 낮잠타임😴 #고양이 #낮잠 #페르시안',
      createdAt: DateTime.now().subtract(Duration(hours: 6)),
      likeCount: 1100,
      commentCount: 73,
      ownerId: 'user4',
      ownerName: '최햄스터',
      ownerProfileImage: 'assets/profiles/profile4.jpg',
      tags: ['#고양이', '#낮잠', '#페르시안'],
    ),
    PetVideo(
      id: 'video5',
      videoUrl: 'assets/videos/video5.mp4',
      petName: '콩이',
      petType: '강아지',
      breed: '시바견',
      description: '콩이의 공원 산책🌳 #시바견 #산책 #공원',
      createdAt: DateTime.now().subtract(Duration(hours: 3)),
      likeCount: 750,
      commentCount: 41,
      ownerId: 'user5',
      ownerName: '정펫맘',
      ownerProfileImage: 'assets/profiles/profile5.jpg',
      tags: ['#시바견', '#산책', '#공원'],
    ),
    PetVideo(
      id: 'video6',
      videoUrl: 'assets/videos/video6.mp4',
      petName: '보리',
      petType: '강아지',
      breed: '웰시코기',
      description: '보리의 애교타임💕 #웰시코기 #애교 #강아지',
      createdAt: DateTime.now().subtract(Duration(hours: 1)),
      likeCount: 1500,
      commentCount: 92,
      ownerId: 'user6',
      ownerName: '강댕댕',
      ownerProfileImage: 'assets/profiles/profile6.jpg',
      tags: ['#웰시코기', '#애교', '#강아지'],
    ),
  ];

  // 댓글 더미 데이터
  static final List<Comment> comments = [
    Comment(
      id: 'comment1',
      videoId: 'video1',
      userId: 'user2',
      userName: '박냥냥',
      userProfileImage: 'assets/profiles/profile2.jpg',
      content: '너무 귀여워요! 😍',
      createdAt: DateTime.now().subtract(Duration(hours: 5)),
      replies: [
        Comment(
          id: 'reply1',
          videoId: 'video1',
          userId: 'user1',
          userName: '김멍멍',
          userProfileImage: 'assets/profiles/profile1.jpg',
          content: '감사합니다 ☺️',
          createdAt: DateTime.now().subtract(Duration(hours: 4)),
          parentId: 'comment1',
        ),
      ],
    ),
    Comment(
      id: 'comment2',
      videoId: 'video1',
      userId: 'user3',
      userName: '이토끼',
      userProfileImage: 'assets/profiles/profile3.jpg',
      content: '산책하는 모습이 너무 신나보여요~',
      createdAt: DateTime.now().subtract(Duration(hours: 3)),
    ),
    Comment(
      id: 'comment3',
      videoId: 'video2',
      userId: 'user4',
      userName: '최햄스터',
      userProfileImage: 'assets/profiles/profile4.jpg',
      content: '장난감과 잘 놀아주네요 🐱',
      createdAt: DateTime.now().subtract(Duration(hours: 6)),
      replies: [
        Comment(
          id: 'reply2',
          videoId: 'video2',
          userId: 'user2',
          userName: '박냥냥',
          userProfileImage: 'assets/profiles/profile2.jpg',
          content: '까미가 장난감을 정말 좋아해요!',
          createdAt: DateTime.now().subtract(Duration(hours: 5)),
          parentId: 'comment3',
        ),
      ],
    ),
    Comment(
      id: 'comment4',
      videoId: 'video2',
      userId: 'user5',
      userName: '정펫맘',
      userProfileImage: 'assets/profiles/profile5.jpg',
      content: '러시안블루 고양이 너무 이쁘네요 😻',
      createdAt: DateTime.now().subtract(Duration(hours: 4)),
    ),
    Comment(
      id: 'comment5',
      videoId: 'video3',
      userId: 'user6',
      userName: '강댕댕',
      userProfileImage: 'assets/profiles/profile6.jpg',
      content: '말티즈 털 관리 팁 좀 알려주세요!',
      createdAt: DateTime.now().subtract(Duration(hours: 7)),
      replies: [
        Comment(
          id: 'reply3',
          videoId: 'video3',
          userId: 'user3',
          userName: '이토끼',
          userProfileImage: 'assets/profiles/profile3.jpg',
          content: '매일 빗질해주고 2주에 한 번 목욕해요~',
          createdAt: DateTime.now().subtract(Duration(hours: 6)),
          parentId: 'comment5',
        ),
      ],
    ),
    Comment(
      id: 'comment6',
      videoId: 'video3',
      userId: 'user7',
      userName: '윤멍냥',
      userProfileImage: 'assets/profiles/profile7.jpg',
      content: '목욕하는 모습이 너무 얌전하네요 👍',
      createdAt: DateTime.now().subtract(Duration(hours: 5)),
    ),
    Comment(
      id: 'comment7',
      videoId: 'video4',
      userId: 'user8',
      userName: '조뽀삐',
      userProfileImage: 'assets/profiles/profile8.jpg',
      content: '페르시안 고양이 너무 우아해요',
      createdAt: DateTime.now().subtract(Duration(hours: 3)),
    ),
    Comment(
      id: 'comment8',
      videoId: 'video4',
      userId: 'user9',
      userName: '한냥이',
      userProfileImage: 'assets/profiles/profile9.jpg',
      content: '낮잠 자는 모습이 천사같아요~ 💕',
      createdAt: DateTime.now().subtract(Duration(hours: 2)),
    ),
    Comment(
      id: 'comment9',
      videoId: 'video5',
      userId: 'user10',
      userName: '송펫집사',
      userProfileImage: 'assets/profiles/profile10.jpg',
      content: '공원이 어디인가요? 저희도 가보고 싶어요!',
      createdAt: DateTime.now().subtract(Duration(hours: 1)),
      replies: [
        Comment(
          id: 'reply4',
          videoId: 'video5',
          userId: 'user5',
          userName: '정펫맘',
          userProfileImage: 'assets/profiles/profile5.jpg',
          content: '서울숲이에요~ 강아지 산책하기 좋아요!',
          createdAt: DateTime.now().subtract(Duration(minutes: 30)),
          parentId: 'comment9',
        ),
      ],
    ),
    Comment(
      id: 'comment10',
      videoId: 'video5',
      userId: 'user1',
      userName: '김멍멍',
      userProfileImage: 'assets/profiles/profile1.jpg',
      content: '시바견 산책 모습이 너무 당당해요! 🐕',
      createdAt: DateTime.now().subtract(Duration(minutes: 45)),
    ),
    Comment(
      id: 'comment11',
      videoId: 'video6',
      userId: 'user2',
      userName: '박냥냥',
      userProfileImage: 'assets/profiles/profile2.jpg',
      content: '웰시코기 귀여워요~ 🦊',
      createdAt: DateTime.now().subtract(Duration(minutes: 20)),
    ),
    Comment(
      id: 'comment12',
      videoId: 'video6',
      userId: 'user3',
      userName: '이토끼',
      userProfileImage: 'assets/profiles/profile3.jpg',
      content: '애교가 너무 많네요 ❤️',
      createdAt: DateTime.now().subtract(Duration(minutes: 10)),
    ),
  ];
}
